name: scaile
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24179276428185403
title: Studio Scaile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70285105-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#646464'
    - '#b2b2b2'
    - '#bb2028'
  brandStrength: 0.6875
  lightness: 0.1463567977771163
  saturation: 0.7360267504118383
  rhythmicContrast: 0.6790352105163038
purpose: []
