name: scaile
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23692
title: Studio Scaile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70285105-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2b2b2b'
    - '#696969'
    - '#b1b1b1'
    - '#dddddd'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
