name: scaile
favicon: null
layout_spectrum: 0.97077
typography_spectrum: 0.23692
title: Studio Scaile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70285105-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#646464'
    - '#b2b2b2'
    - '#bb2028'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
